version: "3.1"
services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/camagru.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=matcha_db
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
      APACHE_RUN_DIR: /var/www/html
      
